SET SEARCH_PATH TO BLOOD_BANK;

CREATE TABLE ADMIN (
	ADMIN_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(20),
	NAME VARCHAR(20),
	ADDRESS VARCHAR(100),
	MOBILE VARCHAR(10)
);

CREATE TABLE DONOR (
	DONOR_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(20),	
	NAME VARCHAR(20),
	ADDRESS VARCHAR(100),
	MOBILE VARCHAR(10)
);

CREATE TABLE DOCTOR (
	DOCTOR_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	ADDRESS VARCHAR(100),
	MOBILE VARCHAR(10),
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(20)
);

CREATE TABLE STAFF (
	STAFF_ID SERIAL PRIMARY KEY,
	SALARY INT,
	USERNAME VARCHAR(20), 
	PASSWORD VARCHAR(20),
	POSITION VARCHAR(20),
	DATE_OF_JOINING DATE,
	NAME VARCHAR(20),
	ADDRESS VARCHAR(100),
	MOBILE VARCHAR(10)
);

CREATE TABLE PATIENT(
	PATIENT_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	ADDRESS VARCHAR(100),
	MOBILE VARCHAR(10)
);

CREATE TABLE ITEM (
	ITEM_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	TYPE VARCHAR(20),
	ITEM_COUNT INT,
	PRICE INT
);

CREATE TABLE DONATION_CAMP  (
	CAMP_ID SERIAL PRIMARY KEY,
	EVENT_DATE DATE,
	LOCATION VARCHAR(100),
	START_TIME TIME,
	END_TIME TIME
);

CREATE TABLE INVENTORY (
	CAMP_ID SERIAL,
	ITEM_ID SERIAL,
	COUNT INT,
	PRIMARY KEY (CAMP_ID, ITEM_ID),
	FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID) ON DELETE CASCADE,
	FOREIGN KEY (CAMP_ID) REFERENCES DONATION_CAMP(CAMP_ID) ON DELETE CASCADE
);

CREATE TABLE TEAM (
	CAMP_ID INT,
	STAFF_ID INT,
	FOREIGN KEY (CAMP_ID) REFERENCES DONATION_CAMP(CAMP_ID) ON DELETE CASCADE,
	FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID) ON DELETE CASCADE,
	PRIMARY KEY (CAMP_ID, STAFF_ID)
);

CREATE TABLE BLOOD_PACKET (
	PACKET_ID SERIAL PRIMARY KEY,
	CAPACITY INT,
	CAMP_ID INT,
	DONOR_ID INT,
	USAGE_TYPE VARCHAR(10),
	FOREIGN KEY (CAMP_ID) REFERENCES DONATION_CAMP(CAMP_ID) ON DELETE CASCADE,
	FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID) ON DELETE CASCADE
);

CREATE TABLE BLOOD_REPORT (
	REPORT_ID SERIAL PRIMARY KEY,
	PACKET_ID INT,
	BLOOD_GROUP VARCHAR(4),
	RBC_COUNT NUMERIC(10, 2),
	WBC_COUNT INT,
	PLATELETS VARCHAR(10),
	SUGAR_LEVEL VARCHAR(10),
	HAEMOGLOBIN VARCHAR(10),
	TIME_STAMP TIMESTAMP,
	FOREIGN KEY (PACKET_ID) REFERENCES BLOOD_PACKET(PACKET_ID) ON DELETE CASCADE
);

CREATE TABLE TRANSFUSION (
	PATIENT_ID INT,
	PACKET_ID INT,
	DOCTOR_ID INT,
	TIME_STAMP TIMESTAMP,
	PRIMARY KEY (DOCTOR_ID, TIME_STAMP),
	FOREIGN KEY (PACKET_ID) REFERENCES BLOOD_PACKET(PACKET_ID) ON DELETE CASCADE,
	FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID) ON DELETE CASCADE,
	FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID) ON DELETE CASCADE
);

